version: '3.7'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: leaderboi
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db: